// Export all types for easy importing
export * from './api.types';
export * from './product.types';
export * from './material.types';
export * from './process.types';
// export * from './machine.types';
export * from './operator.types';
export * from './inventory.types';
export * from './client.types';
export * from './supplier.types';
export * from './hr.types';
export * from './finance.types';
export * from './work-order.types';
export * from './purchase-order.types';
// export * from './service-order.types';
export * from './maintenance.types';
// export * from './quote.types';
export * from './order-pedido.types';
export * from './vehicle.types';
export * from './delivery.types';
export * from './gasoline-receipt.types';
