<?php

namespace Database\Seeders;

use App\Models\Supplier;
use Illuminate\Database\Seeder;

class SupplierSeeder extends Seeder
{
    /**
     * Seed the suppliers table.
     */
    public function run(): void
    {
        $suppliers = [
            [
                'code' => 'PROV-001',
                'name' => 'Papeles y Cartones SA de CV',
                'rfc' => 'PCA-850201234',
                'email' => 'ventas@papelescartones.com',
                'phone' => '(55) 2100-1234',
                'address' => 'Av. del Trabajo 150, Col. Iztapalapa',
                'city' => 'Ciudad de México',
                'state' => 'CDMX',
                'contact' => 'Roberto Mendoza',
                'category' => 'materia-prima',
                'lead_time' => 5,
                'rating' => 5,
                'balance' => 0.00,
                'status' => 'active',
            ],
            [
                'code' => 'PROV-002',
                'name' => 'Tintas y Solventes Industriales',
                'rfc' => 'TSI-960315678',
                'email' => 'pedidos@tintasindustriales.com',
                'phone' => '(55) 5533-2211',
                'address' => 'Calle Industrial 45, Col. Azcapotzalco',
                'city' => 'Ciudad de México',
                'state' => 'CDMX',
                'contact' => 'Carmen López',
                'category' => 'insumos',
                'lead_time' => 3,
                'rating' => 4,
                'balance' => 15000.00,
                'status' => 'active',
            ],
            [
                'code' => 'PROV-003',
                'name' => 'Pegamentos Especiales del Centro',
                'rfc' => 'PEC-780501567',
                'email' => 'ventas@pegamentoscentro.com',
                'phone' => '(55) 4455-6677',
                'address' => 'Blvd. de la Luz 80, Col. Tlalpan',
                'city' => 'Ciudad de México',
                'state' => 'CDMX',
                'contact' => 'Pedro Sánchez',
                'category' => 'insumos',
                'lead_time' => 2,
                'rating' => 5,
                'balance' => 5000.00,
                'status' => 'active',
            ],
            [
                'code' => 'PROV-004',
                'name' => 'Maquinaria Industrial del Norte',
                'rfc' => 'MIN-030212987',
                'email' => 'contacto@maquinarianorte.com',
                'phone' => '(81) 8312-3456',
                'address' => 'Av. Guerrero 200, Col. Centro',
                'city' => 'Monterrey',
                'state' => 'Nuevo León',
                'contact' => 'Fernando Torres',
                'category' => 'maquinaria',
                'lead_time' => 30,
                'rating' => 4,
                'balance' => 50000.00,
                'status' => 'active',
            ],
            [
                'code' => 'PROV-005',
                'name' => 'Suministros de Empaque Jalisco',
                'rfc' => 'SEJ-120725431',
                'email' => 'info@suministrosjjalisco.com',
                'phone' => '(33) 3612-7890',
                'address' => 'Calle 5 de Mayo 500, Col. Centro',
                'city' => 'Guadalajara',
                'state' => 'Jalisco',
                'contact' => 'Rosa Hernández',
                'category' => 'empaque',
                'lead_time' => 4,
                'rating' => 4,
                'balance' => 8000.00,
                'status' => 'active',
            ],
            [
                'code' => 'PROV-006',
                'name' => 'Plásticos y Films Industriales',
                'rfc' => 'PFI-880903876',
                'email' => 'ventas@plasticosfilms.com',
                'phone' => '(55) 5678-9012',
                'address' => 'Av. 602 100, Col. Iztacalco',
                'city' => 'Ciudad de México',
                'state' => 'CDMX',
                'contact' => 'Luis García',
                'category' => 'materia-prima',
                'lead_time' => 7,
                'rating' => 5,
                'balance' => 25000.00,
                'status' => 'active',
            ],
            [
                'code' => 'PROV-007',
                'name' => 'Herramientas de Precisión QRO',
                'rfc' => 'HPQ-950612543',
                'email' => 'pedidos@herramientasqro.com',
                'phone' => '(442) 245-6789',
                'address' => 'Av. Tecnológico 1500, Col. Cayetano',
                'city' => 'Santiago de Querétaro',
                'state' => 'Querétaro',
                'contact' => 'Miguel Ángel Ruiz',
                'category' => 'herramientas',
                'lead_time' => 10,
                'rating' => 4,
                'balance' => 12000.00,
                'status' => 'active',
            ],
            [
                'code' => 'PROV-008',
                'name' => 'Cajas y Displays Puebla',
                'rfc' => 'CDP-700215678',
                'email' => 'ventas@cajasdisplay.com',
                'phone' => '(222) 456-7890',
                'address' => 'Calle 11 Sur 300, Col. Residencial',
                'city' => 'Puebla',
                'state' => 'Puebla',
                'contact' => 'Ana Martínez',
                'category' => 'empaque',
                'lead_time' => 5,
                'rating' => 3,
                'balance' => 5000.00,
                'status' => 'active',
            ],
            [
                'code' => 'PROV-009',
                'name' => 'Transportes y Logistica ZM',
                'rfc' => 'TLZ-880401234',
                'email' => 'flota@transporteszm.com',
                'phone' => '(55) 7890-4567',
                'address' => 'Av. Principal 800, Col. Las Armas',
                'city' => 'Ecatepec',
                'state' => 'Estado de México',
                'contact' => 'José Luis Díaz',
                'category' => 'servicios',
                'lead_time' => 1,
                'rating' => 4,
                'balance' => 30000.00,
                'status' => 'active',
            ],
            [
                'code' => 'PROV-010',
                'name' => 'Reciclados del Valle',
                'rfc' => 'RDV-050312987',
                'email' => 'contacto@recicladosvalle.com',
                'phone' => '(55) 3456-7890',
                'address' => 'Carretera Mexico-Toluca km 20, Col. Industrial',
                'city' => 'Toluca',
                'state' => 'Estado de México',
                'contact' => 'María Elena Cruz',
                'category' => 'materia-prima',
                'lead_time' => 3,
                'rating' => 4,
                'balance' => 20000.00,
                'status' => 'active',
            ],
        ];

        foreach ($suppliers as $supplier) {
            Supplier::firstOrCreate(
                ['code' => $supplier['code']],
                $supplier
            );
        }
    }
}
